
server:
  port: 2024  # Set the server port

spring:
  application:
    name: ExpenseTrackerBackend
  datasource:
    url: jdbc:postgresql://localhost:5432/expensetracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use `update` for development; for production, prefer `validate` or `none`
    show-sql: true      # Enable this to log SQL queries in the console
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.PostgreSQLDialect


management:
  endpoints:
    web:
      exposure:
        include:
        - health


